### PR TITLE
Add DevRel City to CFP

### PR DESCRIPTION
**Pull request by Zelig880**
I have added DevRel city to CFP

### CODE REVIEW

**Comment by RCheesley** [comment]
@Zelig880 am I right in the understanding that this requires a monthly paid subscription of $599 to access the CFP resources?

**Comment by Zelig880** [comment]
Hi Ruth, Yes it does.

This is a "tool" for DevRel, but I could not find a better category for it.

**Comment by jerdog** [comment]
This is probably better added to "Other" than CFPs since this looks to be a community management tool of sorts? Never heard of it though

**Comment by davidgs** [comment]
@Zelig880 Have you updated the PR based on the feedback?

**Comment by Zelig880** [comment]
No it is ok to close this now.

**Pull request closed without merging**
