### PR TITLE
Added Mogics Power Bagel

### PR DESCRIPTION
**Pull request by Damovisa**
By far my favourite item I take everywhere!

### CODE REVIEW

**Comment by noelmace** [comment]
Seems like an amazing product indeed.
Would you know about an EU version of this?

**Comment by Damovisa** [comment]
It should be universal! I'm in Australia and the centre section pops out to provide a universal adapter.

**Comment by noelmace** [comment]
I was more thinking about the output, not the input. Seems like it only has US (type A/B) outputs, but as I live in Europe, so all my electrical devices have EU (type C/E/F) plugs.

**Comment by Damovisa** [comment]
Ah, I understand :)
The Donut is the one that has only US type outputs, but the Bagel has (mostly) universal outputs!

image

**Comment by noelmace** [comment]
OOOOhhh OK I didn't notice it used "universal" plugs, perfect! Thx very much :+1:

**Review by RCheesley — APPROVED** [review]

**Pull request merged**
