### PR TITLE
Updated README.md file

### PR DESCRIPTION
**Pull request by SaptarshiSarkar12**
Added link to a website for publishing articles

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@RCheesley @davidgs Please review this PR

**Review by davidgs — APPROVED** [review]

**Comment by SaptarshiSarkar12** [comment]
@davidgs please merge this PR

**Comment by davidgs** [comment]
Have to wait for an owner to approve the workflow to check it. @jerdog or @mary-grace or another workspace maintainer will have to do that.

**Comment by SaptarshiSarkar12** [comment]
> Have to wait for an owner to approve the workflow to check it. @jerdog or @mary-grace or another workspace maintainer will have to do that.

Ok @davidgs

**Pull request merged**
