### PR TITLE
Add Slack Etiquette template

### PR DESCRIPTION
**Pull request by mhall119**
Creates a new ./templates/ directory for gathering resources that can be reused by other communities. Starting with a Slack Etiquette guide from SparkPost.

### CODE REVIEW

**Review by mbbroberg — COMMENTED** [review]
This looks really great @mhall119, thank you for sharing!

One point to clarify: is the license required to be in the repository, or could we link to https://creativecommons.org/ directly?

**Comment by mhall119** [comment]
> This looks really great @mhall119, thank you for sharing!
> 
> One point to clarify: is the license required to be in the repository, or could we link to https://creativecommons.org/ directly?

There was already a LICENSE.MD in the root of the repository, but it wasn't the correct one for these template files because it was the Non-Commrecial CC variant. I included the one I did to match what was already being done in this repo.

**Comment by mhall119** [comment]
There was some other question about the license file in the repo root though, I created an issue #40 to get that addressed.

**Review by mbbroberg — APPROVED** [review]
LGTM

**Pull request merged**
